services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    privileged: true
    working_dir: /var/www/html
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nextcloud:/var/www/html
      - ${PWD}/certificates:/certificates
      - ${PWD}/transfer-src/.config:/var/www/html/config
      - ${PWD}/transfer/transfer:/var/www/html/transfer
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: ["/bin/bash", "-c" , "chown -R 33:33 /var/www/html/config && chmod -R 755 /var/www/html/config && chown -R 33:33 /certificates && chmod -R 755 /certificates && /entrypoint.sh apache2-foreground "]
    environment:
      - UID=33
      - GID=33
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db


volumes:
  db:
  nextcloud:
