services:
  db:
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    restart: always
    working_dir: /var/www/html
    user: 1001:118
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
      - /certificates:/certificates
      - /transfer-src/.config:/var/www/html/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - UID=1001
      - GID=118
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db


volumes:
  db:
  nextcloud:
