name: Build and Publish

on:
  push:
    branches:
      - master
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Node.js
      uses: actions/setup-node@main

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: make

    - name: Archive app
      run: |
        make dist
        ls -lah 

    - name: Save build artifacts
      uses: actions/upload-artifact@main
      with:
        name: build-artifacts
        path: ./nextcloud-transfer.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Determine if it is a release or pre-release
      id: determine_release_type
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v*.*.* ]]; then
          echo "release_type=false" >> $GITHUB_ENV
        else
          echo "release_type=true" >> $GITHUB_ENV
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release of the app.
        draft: false
        prerelease: ${{ env.release_type }}

    - name: Download build artifacts
      uses: actions/download-artifact@main
      with:
        name: build-artifacts
      
    - name: Generate signature
      run: |
        openssl dgst -sha512 -sign ${{ secrets.SIGNING_KEY }} -out nextcloud-transfer.tar.gz.sig nextcloud-transfer.tar.gz
        openssl base64 -in nextcloud-transfer.tar.gz.sig -out nextcloud-transfer.tar.gz.sig.base64

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@main
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nextcloud-transfer.tar.gz
        asset_name: nextcloud-transfer.tar.gz
        asset_content_type: application/gzip

    - name: Upload signature
      uses: actions/upload-release-asset@main
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nextcloud-transfer.tar.gz.sig.base64
        asset_name: nextcloud-transfer.tar.gz.sig.base64
        asset_content_type: text/plain
